[package]
name = "desktop_screenstate_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "desktop_screenstate_rs"
crate-type = ["cdylib"]

[dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Power",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
